export enum DBTable {
  USERS = "users",
  ROLES = "roles",
  CUSTOMERS = "customers",
  ORDERS = "orders",
  ORDER_ITEMS = "orderitems",
  PRODUCTS = "products",
  BRANDS = "brands",
  CATEGORIES = "categories",
  PRODUCT_TYPES = "producttypes",
  PROMOTIONS = "promotions",
  PROMOTION_PHASES = "promotionphases",
  RETURNS = "returns",
  COLORS = "colors",
  SUPPLIERS = "suppliers",
  INVENTORY = "inventory",
  SIZES = "sizes",
  REVIEWS = "reviews",
  REFRESH_TOKENS = "refreshtokens",
  CART = "shoppingcart",
  CART_ITEMS = "cartitems",
}
